<?php 
require_once __DIR__ . "/../reverse-whois-api/config_util.php";
$WHOIS_CURRENT_INDEX="whois_current_index";
$WHOIS_HISTORY_INDEX="whois_history_index";
$MAX_DOMAIN_SEARCH_MATCH = 10000;
$MAX_SEARCH_CUTOFF = 10000;
$SHOW_QUERY_TIME = 1;
$SNIPPET_INDEX="test_v7_index";


//# database connect information
$DBUSER = "reader_dev";
$DBPASS = "RQgTQxGzzTeA";
$DBHOST = "107.182.166.186:9306";
$DB="mysql41";

$RW_WHOISAPI_DB     = "whoisapi";
$RW_WHOISAPI_DBUSER = "reader_dev";
$RW_WHOISAPI_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISAPI_DBHOST = "localhost";

$RW_WHOISCRAWLER_DB     = "whoiscrawler2";
$RW_WHOISCRAWLER_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_DBHOST = "192.95.33.45";

$RW_WHOISCRAWLER_UPDATE1_DB     = "whoiscrawler_update_1";
$RW_WHOISCRAWLER_UPDATE1_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_UPDATE1_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_UPDATE1_DBHOST = "64.150.176.240";

$RW_WHOISCRAWLER_UPDATE2_DB     = "whoiscrawler_update_2";
$RW_WHOISCRAWLER_UPDATE2_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_UPDATE2_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_UPDATE2_DBHOST = "64.150.176.240";

$RW_WHOISCRAWLER_UPDATE3_DB     = "whoiscrawler_update_10003";
$RW_WHOISCRAWLER_UPDATE3_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_UPDATE3_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_UPDATE3_DBHOST = "64.150.176.240";

$RW_WHOISCRAWLER_SPECIAL_UPDATE1_DB     = "whoiscrawler_special_update_1";
$RW_WHOISCRAWLER_SPECIAL_UPDATE1_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_SPECIAL_UPDATE1_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_SPECIAL_UPDATE1_DBHOST = "64.150.176.240";

$RW_WHOISCRAWLER_V1_DB    = "whoiscrawler";  
$RW_WHOISCRAWLER_V1_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_V1_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_V1_DBHOST = "168.143.87.114";

$RW_WHOIS_API_DB2_DB    = "whoiscrawler"; 
$RW_WHOIS_API_DB2_DBUSER = "reader_dev";
$RW_WHOIS_API_DB2_DBPASS = "RQgTQxGzzTeA";
$RW_WHOIS_API_DB2_DBHOST = "206.80.35.74";

$RW_WHOISCRAWLER_CODERO2_DB    = "whoiscrawler";
$RW_WHOISCRAWLER_CODERO2_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_CODERO2_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_CODERO2_DBHOST = "64.150.189.64";

$RW_WHOISCRAWLER_CA_V1_DB = "ca_v1";
$RW_WHOISCRAWLER_CA_V1_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_CA_V1_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_CA_V1_DBHOST = "198.27.74.137";

$RW_WHOISCRAWLER_DE_V1_DB = "de_v1";
$RW_WHOISCRAWLER_DE_V1_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_DE_V1_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_DE_V1_DBHOST = "198.27.74.137";

$RW_WHOISCRAWLER_FR_V1_DB = "fr_v1";
$RW_WHOISCRAWLER_FR_V1_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_FR_V1_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_FR_V1_DBHOST = "198.27.74.137";

$RW_WHOISCRAWLER_IE_V1_DB = "ie_v1";
$RW_WHOISCRAWLER_IE_V1_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_IE_V1_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_IE_V1_DBHOST = "198.27.74.137";

$RW_WHOISCRAWLER_IN_V1_DB = "in_v1";
$RW_WHOISCRAWLER_IN_V1_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_IN_V1_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_IN_V1_DBHOST = "198.27.74.137";

$RW_WHOISCRAWLER_UK_V1_DB = "uk_v1";
$RW_WHOISCRAWLER_UK_V1_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_UK_V1_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_UK_V1_DBHOST = "198.27.74.137";

$RW_WHOISCRAWLER_UK_V2_DB = "uk_v2";
$RW_WHOISCRAWLER_UK_V2_DBUSER = "reader_dev";
$RW_WHOISCRAWLER_UK_V2_DBPASS = "RQgTQxGzzTeA";
$RW_WHOISCRAWLER_UK_V2_DBHOST = "198.27.74.137";


$RW_WHOISCRAWLER_V3_DBUSER ="reader_dev";
$RW_WHOISCRAWLER_V3_DBPASS ="RQgTQxGzzTeA";
$RW_WHOISCRAWLER_V3_DBHOST ="192.95.33.45";

$RW_WHOISCRAWLER_V3_COM_DB = "whoiscrawler_v3_com";
$RW_WHOISCRAWLER_V3_NET_DB = "whoiscrawler_v3_net";
$RW_WHOISCRAWLER_V3_ORG_DB = "whoiscrawler_v3_org";
$RW_WHOISCRAWLER_V3_INFO_DB = "whoiscrawler_v3_info";
$RW_WHOISCRAWLER_V3_US_DB = "whoiscrawler_v3_us";
$RW_WHOISCRAWLER_V3_BIZ_DB = "whoiscrawler_v3_biz";
$RW_WHOISCRAWLER_V3_MOBI_DB = "whoiscrawler_v3_mobi";
$RW_WHOISCRAWLER_V3_PRO_DB = "whoiscrawler_v3_pro";
$RW_WHOISCRAWLER_V3_COOP_DB = "whoiscrawler_v3_coop";

$RW_WHOISCRAWLER_DBS = array('0'=>db_param_struct($RW_WHOISCRAWLER_DB, $RW_WHOISCRAWLER_DBUSER, $RW_WHOISCRAWLER_DBPASS,$RW_WHOISCRAWLER_DBHOST), //db v2 
							'2000000000'=>db_param_struct($RW_WHOISCRAWLER_V1_DB, $RW_WHOISCRAWLER_V1_DBUSER, $RW_WHOISCRAWLER_V1_DBPASS,$RW_WHOISCRAWLER_V1_DBHOST), //db v1, not available in both index and database, resurrect it someday
							 
							'3000000000'=>db_param_struct($RW_WHOISCRAWLER_UPDATE1_DB, $RW_WHOISCRAWLER_UPDATE1_DBUSER, $RW_WHOISCRAWLER_UPDATE1_DBPASS,$RW_WHOISCRAWLER_UPDATE1_DBHOST),
							'3100000000'=>db_param_struct($RW_WHOISCRAWLER_UPDATE2_DB, $RW_WHOISCRAWLER_UPDATE2_DBUSER, $RW_WHOISCRAWLER_UPDATE2_DBPASS,$RW_WHOISCRAWLER_UPDATE2_DBHOST),
							'3200000000'=>db_param_struct($RW_WHOISCRAWLER_UPDATE3_DB, $RW_WHOISCRAWLER_UPDATE3_DBUSER, $RW_WHOISCRAWLER_UPDATE3_DBPASS,$RW_WHOISCRAWLER_UPDATE3_DBHOST), //updated daily from newly registered domains with whois
						
							'4000000000'=>db_param_struct($RW_WHOISCRAWLER_SPECIAL_UPDATE1_DB, $RW_WHOISCRAWLER_SPECIAL_UPDATE1_DBUSER, $RW_WHOISCRAWLER_SPECIAL_UPDATE1_DBPASS, $RW_WHOISCRAWLER_SPECIAL_UPDATE1_DBHOST), //special one time update that is no longer updated
							
							'5000000000'=>db_param_struct($RW_WHOIS_API_DB2_DB, $RW_WHOIS_API_DB2_DBUSER, $RW_WHOIS_API_DB2_DBPASS, $RW_WHOIS_API_DB2_DBHOST), //old data, availble in index but not in database
							 
							'5200000000'=>db_param_struct($RW_WHOISCRAWLER_CODERO2_DB, $RW_WHOISCRAWLER_CODERO2_DBUSER, $RW_WHOISCRAWLER_CODERO2_DBPASS, $RW_WHOISCRAWLER_CODERO2_DBHOST), //index updated weekly from whoisxmlapi production db on codero2
							 
							'8000000000'=>db_param_struct($RW_WHOISCRAWLER_CA_V1_DB, $RW_WHOISCRAWLER_CA_V1_DBUSER, $RW_WHOISCRAWLER_CA_V1_DBPASS, $RW_WHOISCRAWLER_CA_V1_DBHOST), //start from cctld db
							'8010000000'=>db_param_struct($RW_WHOISCRAWLER_DE_V1_DB, $RW_WHOISCRAWLER_DE_V1_DBUSER, $RW_WHOISCRAWLER_DE_V1_DBPASS, $RW_WHOISCRAWLER_DE_V1_DBHOST),
							'8020000000'=>db_param_struct($RW_WHOISCRAWLER_FR_V1_DB, $RW_WHOISCRAWLER_FR_V1_DBUSER, $RW_WHOISCRAWLER_FR_V1_DBPASS, $RW_WHOISCRAWLER_FR_V1_DBHOST),
							'8030000000'=>db_param_struct($RW_WHOISCRAWLER_IE_V1_DB, $RW_WHOISCRAWLER_IE_V1_DBUSER, $RW_WHOISCRAWLER_IE_V1_DBPASS, $RW_WHOISCRAWLER_IE_V1_DBHOST),
							'8040000000'=>db_param_struct($RW_WHOISCRAWLER_IN_V1_DB, $RW_WHOISCRAWLER_IN_V1_DBUSER, $RW_WHOISCRAWLER_IN_V1_DBPASS, $RW_WHOISCRAWLER_IN_V1_DBHOST),
							'8050000000'=>db_param_struct($RW_WHOISCRAWLER_UK_V1_DB, $RW_WHOISCRAWLER_UK_V1_DBUSER, $RW_WHOISCRAWLER_UK_V1_DBPASS, $RW_WHOISCRAWLER_UK_V1_DBHOST),
							'8060000000'=>db_param_struct($RW_WHOISCRAWLER_UK_V2_DB, $RW_WHOISCRAWLER_UK_V2_DBUSER, $RW_WHOISCRAWLER_UK_V2_DBPASS, $RW_WHOISCRAWLER_UK_V2_DBHOST),
							
							
						   '10000000000'=>db_param_struct($RW_WHOISCRAWLER_V3_COM_DB, $RW_WHOISCRAWLER_V3_DBUSER, $RW_WHOISCRAWLER_V3_DBPASS, $RW_WHOISCRAWLER_V3_DBHOST), //db v3
						   '10200000000'=>db_param_struct($RW_WHOISCRAWLER_V3_NET_DB, $RW_WHOISCRAWLER_V3_DBUSER, $RW_WHOISCRAWLER_V3_DBPASS, $RW_WHOISCRAWLER_V3_DBHOST),
						   '10300000000'=>db_param_struct($RW_WHOISCRAWLER_V3_ORG_DB, $RW_WHOISCRAWLER_V3_DBUSER, $RW_WHOISCRAWLER_V3_DBPASS, $RW_WHOISCRAWLER_V3_DBHOST),
						   '10400000000'=>db_param_struct($RW_WHOISCRAWLER_V3_INFO_DB, $RW_WHOISCRAWLER_V3_DBUSER, $RW_WHOISCRAWLER_V3_DBPASS, $RW_WHOISCRAWLER_V3_DBHOST),
						   '10500000000'=>db_param_struct($RW_WHOISCRAWLER_V3_US_DB, $RW_WHOISCRAWLER_V3_DBUSER, $RW_WHOISCRAWLER_V3_DBPASS, $RW_WHOISCRAWLER_V3_DBHOST),
						   '10600000000'=>db_param_struct($RW_WHOISCRAWLER_V3_BIZ_DB, $RW_WHOISCRAWLER_V3_DBUSER, $RW_WHOISCRAWLER_V3_DBPASS, $RW_WHOISCRAWLER_V3_DBHOST),
						   '10700000000'=>db_param_struct($RW_WHOISCRAWLER_V3_MOBI_DB, $RW_WHOISCRAWLER_V3_DBUSER, $RW_WHOISCRAWLER_V3_DBPASS, $RW_WHOISCRAWLER_V3_DBHOST),
						   '10800000000'=>db_param_struct($RW_WHOISCRAWLER_V3_PRO_DB, $RW_WHOISCRAWLER_V3_DBUSER, $RW_WHOISCRAWLER_V3_DBPASS, $RW_WHOISCRAWLER_V3_DBHOST),
						   '10900000000'=>db_param_struct($RW_WHOISCRAWLER_V3_COOP_DB, $RW_WHOISCRAWLER_V3_DBUSER, $RW_WHOISCRAWLER_V3_DBPASS, $RW_WHOISCRAWLER_V3_DBHOST),		  
							 
							'9223372036854775807'  =>false
							
							);

?>


